### PR TITLE
Test retry strategy when the node is blocking

### PR DESCRIPTION
**Pull request by Adamantios**
## Proposed changes

Create a test whose purpose is to check whether the retry strategy works if a node is blocking, by simulating a blocking time larger than the expected duration of the strategy.

## Fixes

n/a

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

n/a

### CODE REVIEW

**Comment by Adamantios** [comment]
We may investigate if we can replace the [get_transaction_receipt](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_transaction_receipt) with the [wait_for_transaction_receipt](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.wait_for_transaction_receipt) on `open-aea`, because it has a timeout and is potentially not affected by blocking node requests.

**Review by 0xArdi — APPROVED** [review]

**Comment by Adamantios** [comment]
@0xArdi and I believe that there are two potential solutions:

1. Replace the [get_transaction_receipt](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_transaction_receipt) with the [wait_for_transaction_receipt](https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.wait_for_transaction_receipt) on `open-aea`, because it has a timeout and is not affected by blocking node requests. This would also allow us to replace the custom retry logic in our ledger dispatcher, but we would only be able to have a constant backoff.
2. Create our own `wait_for_transaction_receipt` method at the `open-autonomy` so that we do not lose our linear backoff.

(1.) is the cleanest solution, but has the limitation that we would need to wait for an `open-aea` release before fixing the issue.

**Review by 0xArdi — APPROVED** [review]

**Comment by DavidMinarsch** [comment]
Option 1 please.

**Comment by Adamantios** [comment]
Marked as a draft until we resolve the issue on `open-aea` and the fix is included in a release.

**Comment by Adamantios** [comment]
Flaky `test_attempts_get_transaction_receipt` in [[WIP] Test retry strategy when the node is blocking main_workflow #5132](https://github.com/valory-xyz/open-autonomy/runs/8270584723?check_suite_focus=true) is because of a too small value for the `retry_timeout`, which as a result makes the `get_transaction_receipt` to timeout before the mocked method gets called and therefore the count does not increase.

We can increase the timeout at the base branch on #1311 after this gets merged.

**Review by 0xArdi — APPROVED** [review]
noice

**Pull request merged**
