### PR TITLE
Add support for using multiple ledgers in `keys.json`

### PR DESCRIPTION
**Pull request by angrybayblade**
## Proposed changes

This PR adds support for using multiple ledgers in a keys.json file.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes
- [ ] Public-facing documentation has been updated with the changes affected by this PR. Even if the provided contents are not in their final form, all significant information must be included.
- [ ] Any backwards-incompatible/breaking change has been clearly documented in the upgrading document.

### CODE REVIEW

**Comment by angrybayblade** [comment]
@jmoreira-valory @dvilelaf @Adamantios You can define the keys.json file as following to use multiple key types

```json
[
  [
    {
      "address": "4Si...",
      "private_key": "5P1...",
      "ledger": "solana"
    },
    {
      "address": "0x1...",
      "private_key": "0x1...",
      "ledger": "ethereum"
    }
  ],
  [
    {
      "address": "H1R...",
      "private_key": "2T1...",
      "ledger": "solana"
    },
    {
      "address": "0x6...",
      "private_key": "0xc...",
      "ledger": "ethereum"
    }
  ],
  ...
 ]
```

**Review by 0xArdi — COMMENTED** [review]
I cannot determine whether this introduces a breaking change or not. Can you confirm that the current way we provide keys will be still supported?

**Comment by jmoreira-valory** [comment]
> @jmoreira-valory @dvilelaf @Adamantios You can define the keys.json file as following to use multiple key types
> 
> ```json
> [
>   [
>     {
>       "address": "4Si...",
>       "private_key": "5P1...",
>       "ledger": "solana"
>     },
>     {
>       "address": "0x1...",
>       "private_key": "0x1...",
>       "ledger": "ethereum"
>     }
>   ],
>   [
>     {
>       "address": "H1R...",
>       "private_key": "2T1...",
>       "ledger": "solana"
>     },
>     {
>       "address": "0x6...",
>       "private_key": "0xc...",
>       "ledger": "ethereum"
>     }
>   ],
>   ...
>  ]
> ```

How does the framework identify what address goes to what agent ? (e.g., if I make autonomy build deploy --n 1  with 4 ethereum keys and 4 solana keys)

**Review by Adamantios — COMMENTED** [review]
I suggest that we add tests for this new feature before releasing it.

**Comment by angrybayblade** [comment]
> I cannot determine whether this introduces a breaking change or not. Can you confirm that the current way we provide keys will be still supported?

Sorry for the lack of context, yes this is backwards compatible. The old format is till supported.

**Review by jmoreira-valory — APPROVED** [review]

**Pull request merged**
