### PR TITLE
Fix basepython

### PR DESCRIPTION
**Pull request by Adamantios**
## Proposed changes

Fixes basepython for py10 tests.

## Fixes

n/a

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Further comments

n/a

### CODE REVIEW

**Review by angrybayblade — DISMISSED** [review]
Thanks I don't know how I missed this 😅

**Comment by Adamantios** [comment]
This revealed some further issues we need to open.

**Review by DavidMinarsch — CHANGES_REQUESTED** [review]
Seems like there are now some dependency issues as a result. Please address these

**Comment by Adamantios** [comment]
Opened issues for the CI failures and assigned them to the authors of the corresponding tests:
- macos: #989
- windows: #990

The ubuntu test has been fixed on #680, commit 14777e3.

**Review by DavidMinarsch — APPROVED** [review]

**Pull request merged**
