### PR TITLE
Tests: import_all_modules

### PR DESCRIPTION
**Pull request by Karrenbelt**
## Proposed changes

Test importing all modules. 

The idea is simple: there are definition in `__init__.py` files and other files such as `settings.py`, `configurations.py`, etc. Simply importing these will execute their code and in that sense is preferable over using `# pragma: no cover`.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Karrenbelt** [comment]
This will result in failures of the package command tests:
- `TestPackages.test_lock`
- `TestPackages.test_lock_check_fail`

This needs to be investigated. Usage of subprocesses may prevent this, and may well be related to issues #1590 and #1657

**Comment by Karrenbelt** [comment]
the issue is interesting but not relevant. Two of the `packages lock` command tests are flaky
- failures:
    ```
    ================================== FAILURES ===================================
    ___________________________ TestPackages.test_lock ____________________________
    
    self = <tests.test_autonomy.test_cli.test_packages.TestPackages object at 0x000002208433D588>
    
        def test_lock(self) -> None:
            """Test lock"""
        
            target = "autonomy.cli.packages.get_package_manager"
            with mock.patch(target, return_value=mock.MagicMock()) as m:
                with mock.patch("sys.exit") as sys_exit_mock:
                    result = self.run_cli()
                    assert result.exit_code == 0
                    assert "Updating hashes..." in result.stdout
    >               m.assert_called_once()
    
    tests\test_autonomy\test_cli\test_packages.py:45: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    _mock_self = <MagicMock name='get_package_manager' id='2338707430920'>
    
        def assert_called_once(_mock_self):
            """assert that the mock was called only once.
            """
            self = _mock_self
            if not self.call_count == 1:
                msg = ("Expected '%s' to have been called once. Called %s times." %
                       (self._mock_name or 'mock', self.call_count))
    >           raise AssertionError(msg)
    E           AssertionError: Expected 'get_package_manager' to have been called once. Called 0 times.
    
    c:\hostedtoolcache\windows\python\3.7.9\x64\lib\unittest\mock.py:859: AssertionError
    ______________________ TestPackages.test_lock_check_fail ______________________
    
    self = <tests.test_autonomy.test_cli.test_packages.TestPackages object at 0x00000220834CC348>
    
        def test_lock_check_fail(self) -> None:
            """Test lock --check failure"""
        
            DummyPackageManager = namedtuple("DummyPackageManager", "verify")
            return_value = DummyPackageManager(lambda *_, **__: 1)
            target = "autonomy.cli.packages.get_package_manager"
            with mock.patch(target, return_value=return_value):
                result = self.run_cli(("--check",))
    >           assert result.exit_code == 1
    E           assert 0 == 1
    E             +0
    E             -1
    ```

The failures somehow have to do with `"autonomy.cli.packages.get_package_manager"` not being mocked properly. I have pin-pointed the issue somewhat. It has nothing to do with `sys.modules`, `sys.path`, `sys.metapath`. Also cache invalidation using the importlib machinery does not resolve the issue. I find that is one does not import `cli.packages` module as part of the test, there are no failures.

**Comment by DavidMinarsch** [comment]
I don't see the point of this PR. In fact, the modification of `sys.modules` is suboptimal.

**Comment by Karrenbelt** [comment]
> I don't see the point of this PR. In fact, the modification of `sys.modules` is suboptimal.

if you look real closely, you'll see that sys.modules in not modified :eyes: 

The only reason I opened this was to investigate why package lock command failed. It turns out to be an issue with the mock and, as I stated, not relevant. I fully agree with closing this PR.

**Pull request closed without merging**
