### PR TITLE
Registration skill should not be abstract for registration e2e tests

### PR DESCRIPTION
**Pull request by Adamantios**
## Proposed changes

Registration startup tests only use the registration skill without chaining with other skills. Therefore, we need to set its `is_abstract` configuration to `False` in order to load its components, after https://github.com/valory-xyz/open-autonomy/pull/1084.

## Fixes

n/a

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [ ] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

n/a

### CODE REVIEW

**Review by DavidMinarsch — APPROVED** [review]

**Comment by Adamantios** [comment]
> some failing tests, never say this one failing before (Windows, 3.9) `FAILED tests/test_skills/test_abstract_round_abci/test_base.py::test_dict_serializer_is_deterministic`
> 
> please rerun failed tests

I've noticed this test failing (rarely) on CI. I've tried to reproduce this locally before without any luck. Opened issue #1090.

**Comment by Adamantios** [comment]
Unrelated e2e test `tests/test_agents/test_register_reset_abci.py::TestTendermintResetInterrupt` failed. Agent 0 loops into:
```
[INFO] [agent_00000] Tx {TX_HASH} not found!
```

#1073 might be the reason.

**Comment by Karrenbelt** [comment]
> Unrelated e2e test `tests/test_agents/test_register_reset_abci.py::TestTendermintResetInterrupt` failed. Agent 0 loops into:
> 
> ```
> [INFO] [agent_00000] Tx {TX_HASH} not found!
> ```
> 
> #1073 might be the reason.

yes this looks like it might well be related. @dvilelaf can you perhaps give an update on the issue referenced that you opened?

**Comment by dvilelaf** [comment]
> > Unrelated e2e test `tests/test_agents/test_register_reset_abci.py::TestTendermintResetInterrupt` failed. Agent 0 loops into:
> > ```
> > [INFO] [agent_00000] Tx {TX_HASH} not found!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #1073 might be the reason.
> 
> yes this looks like it might well be related. @dvilelaf can you perhaps give an update on the issue referenced that you opened?

@Karrenbelt Marco [is working on it](https://github.com/valory-xyz/open-autonomy/pull/1087) but there seems to be further problems there, may be you or Adamantios can provide further comments there.

**Pull request merged**
