### PR TITLE
Remove hardcoded values

### LINKED ISSUE #1021: Hardcoded values in contracts
not clear what these values represent; `MIN_GAS`, `MIN_GASPRICE` and ...?

https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L212
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L430
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe/contract.py#L456
https://github.com/valory-xyz/open-autonomy/blob/285b699bca07bd9ac21bf26ab7d43ac5d76f6abb/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L147
https://github.com/valory-xyz/open-autonomy/blob/495561dd996aeb1149b06083ff135c4c3c6bd4ea/packages/valory/contracts/multisend/contract.py#L150

### PR DESCRIPTION
**Pull request by Adamantios**
## Proposed changes

Replaces magic values with constants with meaningful descriptions.

## Fixes

Closes #1021.

## Types of changes

What types of changes does your code introduce? (A **breaking change** is a fix or feature that would cause existing functionality and APIs to not work as expected.)
_Put an `x` in the box that applies_

- [ ] Non-breaking fix (non-breaking change which fixes an issue)
- [ ] Breaking fix (breaking change which fixes an issue)
- [ ] Non-breaking feature (non-breaking change which adds functionality)
- [ ] Breaking feature (breaking change which adds functionality)
- [x] Refactor (non-breaking change which changes implementation)
- [ ] Messy (mixture of the above - requires explanation!)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../blob/main/CONTRIBUTING.md) doc
- [x] I am making a pull request against the `main` branch (left side). Also you should start your branch off our `main`.
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have locally run services that could be impacted and they do not present failures derived from my changes

## Further comments

n/a

### CODE REVIEW

**Review by Karrenbelt — COMMENTED** [review]
looks good, there is one more case I don't like and can be part of this same PR imo

https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L141-L143

instead, we should provide `1` as a default value instead of `0`, here:
https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L92

**Comment by Adamantios** [comment]
> looks good, there is one more case I don't like and can be part of this same PR imo
> 
> https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L141-L143
> 
> instead, we should provide `1` as a default value instead of `0`, here:
> 
> https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L92

Good catch!
What if the user provides `0` as an input though? Should we do something like:
```python
# we set a value to avoid triggering the gas estimation during buildTransaction below
tx_parameters["gas"] = Wei(max(gas, 1))
```
?

**Comment by Karrenbelt** [comment]
> > looks good, there is one more case I don't like and can be part of this same PR imo
> > https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L141-L143
> > 
> > instead, we should provide `1` as a default value instead of `0`, here:
> > https://github.com/valory-xyz/open-autonomy/blob/ebd5f05c62275a420f5b3184c9ad4a447c89e325/packages/valory/contracts/gnosis_safe_proxy_factory/contract.py#L92
> 
> Nice catch! What if the user provides `0` as an input though? Should we do something like:
> 
> ```python
> # we set a value to avoid triggering the gas estimation during buildTransaction below
> tx_parameters["gas"] = Wei(max(gas, 1))
> ```
> 
> ?

hmm I would say no. I don't think we should overwrite to 1 if the input is explicitly provided to be zero. 

I should, however, first ask why do we want to prevent gas estimation during `buildTransaction`? If there is a solid reason to avoid this then we should. Leave a comment in the code why it's necessary or important to avoid the estimation prior to `buildTransaction` if so and call it done.

**Comment by 0xArdi** [comment]
@Karrenbelt when a gas estimate is not set when calling `buildTransaction`, by default gas estimation is performed. That throws an error when repricing a tx. More info on the comments in https://github.com/valory-xyz/open-autonomy/pull/1212 .

**Comment by Karrenbelt** [comment]
> @Karrenbelt when a gas estimate is not set when calling `buildTransaction`, by default gas estimation is performed. That throws an error when repricing a tx. More info on the comments in #1212 .

so that's good to know, @Adamantios worth adding as comment to the code?

**Review by DavidMinarsch — APPROVED** [review]

**Review by DavidMinarsch — APPROVED** [review]

**Pull request merged**
